<?php include ('templates/header-main.php'); ?>

<!-- Post Title -->
<section class="post-title">
    <div class="auto-container">
        <h2>Why do we dream?</h2>
        <ul class="post-info">
            <li class="date">9 March 2021</li>
            <li class="cat">Dream</li>
            <li> <a href="social-share.html" class="call-modal theme-btn btn-style-one"> <span
                        class="icon flaticon-share"></span> Share</a></li>
        </ul>
    </div>
</section>
<!-- End Post Title -->

<!-- Blog Single -->
<section class="blog-single">
    <div class="small-container">
        <!-- Post Single -->
        <div class="post-single">
            <figure class="image"><a href="assets/images/resource/press/why do we dream.jpg" class="lightbox-image"><img
                        src="assets/images/resource/press/why do we dream.jpg" alt=""></a></figure>

            <p>The question of why we dream has fascinated scientists and philosophers for thousands of years.</p>
            <p>Still, there is no definitive answer.</p>
            <p>For about 90 minutes to two hours or more each night, every single person dreams. Dreams are
                sometimes straightforward in their meaning to the dreamer. On the other hand, dreams don’t always
                tell a simple story. The field of dream research becomes even more fascinating when people from
                different cultures and backgrounds report having similar dreams.</p>
            <p>Dreams can range from extraordinarily intense or emotional to very vague, fleeting, confusing, or
                even boring. While some dreams seem to have a clear storyline, others appear to make no sense at
                all.</p>
            <p>More broadly, dreams can provide us with insight about things that are preoccupying us, troubling us
                or engaging our thoughts and emotions.</p>
            <h4>Dream theories</h4>
            <p>Some theories suggest that we dream to consolidate our memories, to process our emotions, to express
                our deepest desires, and to gain practice in confronting potential dangers. Other theories again
                suggest that dreaming is essential to mental and emotional well-being. Some scientists also believe
                that dreams serve no real purpose at all.</p>
            <p>Theories of dreaming range from psychiatric disciplines to neurobiology. Let us have a look at some
                of these theories.</p>
            <h4>Dreams provide unconscious expression</h4>
            <p>This theory suggests that dreams represent unconscious thoughts, wish-fulfillment and motivations.
                People may suppress their longings and primitive thoughts, such as aggressive and sexual instincts,
                which may then appear in dreams. Research refers to this as a dream rebound effect, where
                suppression of something tends to result in dreaming about it.</p>
            <p>Dreams a byproduct of mental processing</p>
            <p>Many experts believe that dreams play an important role in processing our emotions and stressful
                experiences. The brain synthesizes and interprets our emotions, sensations, and memories and then
                attempts to find meaning in these signals through our dreams.</p>
            <p>This model suggests that dreams are a subjective interpretation of these signals generated by the
                brain during sleep and that our active minds, when we wake, are able to pull together the various
                images and memory fragments of the dream to create an organized storyline.</p>
            <h4>The memory filter</h4>
            <p>While we are awake, we accumulate a multitude of data and memories. According to this theory, when we
                dream, our brains sort, condense and file away all that information. This process shows up as
                fragments in our sleeping minds as images, impressions, stories that echo all of the activity and
                thoughts going on in our lives.</p>
            <p>Under this theory, your weird or nonsensical dream may be a flash of memories as they are erased or
                mixed with others that are destined for long-term storage.</p>
            <h4>Dreams prepare and protect</h4>
            <p>This theory proposes that we dream to better prepare ourselves and to confront dangers in the real
                world. For example, a dream in a threat simulation provides the dreamer a safe environment in which
                to practice important skills. While dreaming, we hone our fight or flight instincts to give us an
                increased potential for survival and build mental capability for handling such scenarios if they
                happen for real.</p>
            <p>Dreams help to process emotions</p>
            <p>Dreams can help us process and cope with our emotions or trauma in the safe space. The part of our
                brain that is involved with the experiencing of emotions is active during vivid and intense
                dreaming. There is a strong link between dreaming, memory storage and emotional processing. It also
                explains why dreams are emotionally vivid when we’ve had past emotional or traumatic experiences.
            </p>
            <h4>Lucid dreaming</h4>
            <p>Lucid dreams are dreams in which you have awareness of being in a dream. Often you have some control
                to direct the dream content. These dreams are relatively rare. Around 50% of people recall having
                had at least one lucid dream in their lifetime, while just over 10% report having them regularly.
            </p>
            <p>There is a strong link between lucid dreaming and highly creative output. Research has shown that
                lucid dreamers perform better on creative tasks than those who do not experience lucid dreaming.</p>
            <p>How do we interpret the meaning of some dreams?</p>
            <p>Dreams are one of the most fascinating and mysterious parts of the human experience. Interpretation
                of dreams can give us a good indication of what may be currently happening in our subconscious mind.
            </p>
            <h4>Falling dreams</h4>
            <p>All of us have had these dreams. Some psychologists believe that a falling dream indicates that you
                are hanging on too tightly to a particular situation, or that you need to relax and let go of it.
                Another explanation suggests that it indicates a situation in your life where you are lacking or
                losing control and where you are feeling overwhelmed. Each falling dream represents a path to a core
                part of yourself and by understanding the meaning of your particular falling dream, you may get
                closer to your core.</p>
            <h4>Being chased dreams</h4>
            <p>This is one of the most commonly reported dreams. The reason for these dreams does not come from the
                fear of actually being chased, but rather what we’re running from. These dreams may, therefore, help
                us to understand that we may not be addressing something in our waking lives that require our
                attention.</p>
            <h4>Paralysis</h4>
            <p>The body is in fact encountering a form of paralysis during dreaming, which prevents it from
                physically performing the actions occurring in their dreams. Therefore, dreaming about paralysis
                frequently represents the overlap between the REM stage and the waking stage of sleep. Dreaming
                about paralysis may also indicate that the dreamer feels he / she lacks control over something in
                their waking life.</p>
            <h4>House dreams</h4>
            <p>A house may represent the dreamer’s mind. Different levels or rooms may relate to different aspects
                of the person and different degrees of consciousness. The basement often represents what has been
                neglected, or what the person is not aware of in his / her waking life. Bedrooms may again relate to
                intimate thoughts and feelings.</p>
            <h4>Stress dreams</h4>
            <p>Stressful experiences tend to show up with great frequency in our dreams. Stress dreams may be
                described in many ways, from sad to scary and also nightmares. Experts do not fully understand how
                or why specific stressful dream content ends up in our dreams.<br>People who experience greater
                levels of worry in their daily lives and people with post-traumatic stress disorder (PTSD) report a
                higher frequency and the intensity of nightmares.</p>
            <p>Studies have also shown that people with mental health disorders, such as anxiety and depression,
                tend to have more distressful dreams. Researchers speculate that stress dreams maybe the brain’s
                attempt to help us cope with and make sense of stressful experiences.</p>
            <h4>Benefits of dreaming</h4>
            <p>Neuroscientists today are continuing to explore dreams, dream interpretation and are finding many
                health benefits.</p>
            <p>Have you ever fallen asleep, unsure about a decision? Then when you woke up, the answer somehow
                became clear?</p>
            <p>We all know the expression “let me sleep on it”, but there is actually scientific evidence to support
                that we, in fact, learn and process information while we sleep.</p>
            <p>According to researchers at Harvard Medical School, if you learn a task and then sleep, you may be 10
                times better at that activity than if you had stayed awake, as dreaming helps your brain make sense
                of new information.</p>
            <h4>Good to know</h4>
            <p>Some people who experience severe nightmares on a regular basis may benefit from talking to a
                psychologist or a psychiatrist. Speak to your medical aid. Most Medical aid plans will provide some kind
                of out-of-hospital consultations unless you are on a hospital plan. Both affordable medical aid options, as well as comprehensive medical aid options
                with medical savings, usually offer benefits in this regard from your available medical savings account.&nbsp;&nbsp; </p>
            <p>By Elmarie Jensen</p>

            <ul class="post-tags">
                <li><a href="#">Dreams</a></li>
                <li><a href="#">Health</a></li>
                <li><a href="#">Insightfull</a></li>
            </ul>
        </div>

        <!-- Post Control -->
        <div class="post-control">
            <div class="prev-post">
                <span class="icon flaticon-left"></span>
                <span class="title">Previous Post</span>
                <h5><a href="#">How to self-regulate sensory overload</a></h5>
            </div>
            <div class="next-post">
                <span class="icon flaticon-right"></span>
                <span class="title">Next Post</span>
                <h5><a href="#">What will the top 7 hospital plans in SA cost in 2021?</a></h5>
            </div>
        </div>

    </div>
</section>
<!-- End Blog Single -->
<?php include ('templates/footer.php'); ?>